#!/usr/bin/env python3
"""zronOS x MuJoCo compatibility harness.

For every robot model in the MuJoCo Menagerie this:
  1. loads the real MJCF in MuJoCo (via the zron<->MuJoCo bridge),
  2. introspects its actuators + control ranges,
  3. generates a zronOS manifest and a Robot Chalao (.rc) driver that computes a
     neutral setpoint for every actuator (the language does the arithmetic),
  4. boots that manifest under the real `zron` binary,
  5. parses the setpoints zron commanded and steps them through MuJoCo physics,
  6. checks the simulation stays finite.

It writes a compatibility matrix (compat.md + compat.json). It is honest: a row
is only "PASS" if MuJoCo loaded the model, zron booted the generated driver, the
setpoint count matched the actuator count, and the physics stayed finite.

Usage: python3 compat.py <menagerie_dir> <zron_binary> <out_dir> [--limit N]
"""
import glob, json, os, re, subprocess, sys, tempfile

BRIDGE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "zron_mujoco.py")
PY = os.environ.get("ZRON_PY", sys.executable)

CATEGORIES = [
    ("hand",      ["hand", "leap", "shadow", "dexee", "gripper", "2f85", "softfoot", "wave"]),
    ("quadruped", ["anymal", "spot", "go1", "go2", "a1", "barkour", "cassie", "b1", "aliengo"]),
    ("humanoid",  ["humanoid", "talos", "apollo", "adam", "op3", "h1", "g1", "t1", "n1", "toddlerbot", "rby1", "tidybot", "human", "berkeley"]),
    ("drone",     ["crazyflie", "skydio", "x2", "quad", "drone"]),
    ("arm",       ["gen3", "panda", "fr3", "iiwa", "sawyer", "xarm", "lite6", "piper", "rizon", "vx300", "wx250", "so100", "so101", "so_arm", "yam", "l5", "ur5", "ur10", "arm", "wxai"]),
    ("mobile",    ["stretch", "tiago", "robot", "soccer", "kit", "devarm"]),
]

def categorize(name):
    n = name.lower()
    for cat, keys in CATEGORIES:
        if any(k in n for k in keys):
            return cat
    return "other"

def pick_model(d):
    scenes = sorted(glob.glob(os.path.join(d, "scene*.xml")))
    if scenes:
        return scenes[0]
    xmls = [x for x in sorted(glob.glob(os.path.join(d, "*.xml")))
            if "mjx" not in os.path.basename(x).lower()]
    return xmls[0] if xmls else None

def bridge_call(model_path, requests, timeout=90):
    """Run the bridge, send requests (list of dicts), collect JSON replies."""
    payload = "".join(json.dumps(r) + "\n" for r in requests)
    p = subprocess.run([PY, BRIDGE, model_path], input=payload,
                       capture_output=True, text=True, timeout=timeout)
    replies = []
    for line in p.stdout.splitlines():
        line = line.strip()
        if line.startswith("{"):
            try:
                replies.append(json.loads(line))
            except Exception:
                pass
    return replies, p.stderr

def gen_manifest(tmp, name, ranges):
    """Write a manifest + .rc driver that commands a neutral setpoint per actuator."""
    rc = [f'robot jodo "{name}"']
    for i, (lo, hi) in enumerate(ranges):
        rc.append(f'dikhao "CTRL", {i}, ({lo} + {hi}) / 2')
    rc.append('sehat theek')
    rc.append(f'dikhao "actuators driven:", {len(ranges)}')
    with open(os.path.join(tmp, "driver.rc"), "w") as f:
        f.write("\n".join(rc) + "\n")
    man = ("# auto-generated by the zronOS MuJoCo compatibility harness\n"
           "[service driver]\nscript = driver.rc\nrate_hz = 0\nrestart = never\nautostart = true\n")
    mpath = os.path.join(tmp, "robot.manifest")
    with open(mpath, "w") as f:
        f.write(man)
    return mpath

def run_zron(zron, manifest):
    p = subprocess.run([zron, "demo", "--seconds", "0.5", manifest],
                       capture_output=True, text=True, timeout=30)
    out = p.stdout + p.stderr
    ctrl = {}
    for m in re.finditer(r"CTRL (\-?\d+) (\S+)", out):
        try:
            ctrl[int(m.group(1))] = float(m.group(2))
        except Exception:
            pass
    booted = "boot complete" in out
    clean = ("FAILED" not in out) and ("parse error" not in out) and ("Bhai" not in out)
    vec = [ctrl[i] for i in sorted(ctrl)]
    return booted, clean, vec

def test_model(name, path, zron):
    row = {"model": name, "category": categorize(name), "file": os.path.basename(path),
           "nu": 0, "dof": 0, "nsensor": 0, "nbody": 0,
           "mujoco_load": False, "zron_boot": False, "setpoints_match": False,
           "physics_finite": False, "pass": False, "note": ""}
    # 1. load + info
    try:
        reps, err = bridge_call(path, [{"cmd": "info"}])
    except subprocess.TimeoutExpired:
        row["note"] = "bridge timeout on load"; return row
    if not reps or not reps[0].get("ok"):
        row["note"] = "MuJoCo load failed"; return row
    if len(reps) < 2 or not reps[1].get("ok"):
        row["note"] = "info failed"; row["mujoco_load"] = True; return row
    info = reps[1]
    row.update(mujoco_load=True, nu=info["nu"], dof=info["dof"],
               nsensor=info["nsensor"], nbody=info["nbody"])
    ranges = info["ctrlrange"]
    # 2. generate + boot zron
    with tempfile.TemporaryDirectory() as tmp:
        man = gen_manifest(tmp, name, ranges)
        try:
            booted, clean, vec = run_zron(zron, man)
        except subprocess.TimeoutExpired:
            row["note"] = "zron timeout"; return row
    row["zron_boot"] = booted and clean
    row["setpoints_match"] = (len(vec) == info["nu"])
    # 3. step the commanded setpoints through MuJoCo
    try:
        reps, err = bridge_call(path, [{"cmd": "step", "ctrl": vec, "n": 200}])
    except subprocess.TimeoutExpired:
        row["note"] = "bridge timeout on step"; return row
    if reps and reps[-1].get("ok"):
        row["physics_finite"] = bool(reps[-1].get("finite"))
    row["pass"] = all([row["mujoco_load"], row["zron_boot"],
                       row["setpoints_match"], row["physics_finite"]])
    if row["pass"] and not row["note"]:
        row["note"] = f"{row['nu']} actuators driven, {200} steps stable"
    return row

def main():
    if len(sys.argv) < 4:
        print(__doc__); return 2
    men, zron, out = sys.argv[1], sys.argv[2], sys.argv[3]
    limit = None
    if "--limit" in sys.argv:
        limit = int(sys.argv[sys.argv.index("--limit") + 1])
    os.makedirs(out, exist_ok=True)
    dirs = sorted(d for d in glob.glob(os.path.join(men, "*"))
                  if os.path.isdir(d) and os.path.basename(d) not in
                  ("assets", "python", "test") and pick_model(d))
    if limit:
        dirs = dirs[:limit]
    rows = []
    for i, d in enumerate(dirs, 1):
        name = os.path.basename(d)
        path = pick_model(d)
        try:
            row = test_model(name, path, zron)
        except Exception as e:
            row = {"model": name, "category": categorize(name), "pass": False,
                   "note": f"harness error: {str(e)[:60]}", "nu": 0, "dof": 0,
                   "nsensor": 0, "nbody": 0, "mujoco_load": False, "zron_boot": False,
                   "setpoints_match": False, "physics_finite": False,
                   "file": os.path.basename(path)}
        rows.append(row)
        mark = "PASS" if row["pass"] else "----"
        print(f"[{i:2d}/{len(dirs)}] {mark}  {name:26s} nu={row['nu']:3d} dof={row['dof']:3d}  {row['note']}")
    write_reports(rows, out)
    npass = sum(1 for r in rows if r["pass"])
    print(f"\n{npass}/{len(rows)} models PASS")
    return 0

def write_reports(rows, out):
    with open(os.path.join(out, "compat.json"), "w") as f:
        json.dump(rows, f, indent=2)
    npass = sum(1 for r in rows if r["pass"])
    by_cat = {}
    for r in rows:
        c = r["category"]; by_cat.setdefault(c, [0, 0]); by_cat[c][1] += 1
        if r["pass"]: by_cat[c][0] += 1
    md = []
    md.append("# zronOS x MuJoCo compatibility matrix\n")
    md.append(f"**{npass} / {len(rows)}** open-source MuJoCo Menagerie robot models boot and run "
              "under zronOS through the bridge (real MuJoCo physics).\n")
    md.append("Each model is loaded in MuJoCo, introspected for its actuators, driven by an "
              "auto-generated Robot Chalao service under the real `zron` binary, and stepped "
              "200 times through physics with the setpoints zron commanded. A row passes only if "
              "MuJoCo loaded it, zron booted the driver, the setpoint count matched the actuator "
              "count, and the state stayed finite.\n")
    md.append("## By category\n")
    md.append("| category | pass / total |")
    md.append("|---|---|")
    for c in sorted(by_cat):
        md.append(f"| {c} | {by_cat[c][0]} / {by_cat[c][1]} |")
    md.append("\n## All models\n")
    md.append("| model | category | actuators | DOF | sensors | MuJoCo load | zron boot | setpoints | physics | result |")
    md.append("|---|---|---|---|---|---|---|---|---|---|")
    def y(b): return "yes" if b else "no"
    for r in sorted(rows, key=lambda x: (x["category"], x["model"])):
        md.append(f"| `{r['model']}` | {r['category']} | {r['nu']} | {r['dof']} | {r['nsensor']} | "
                  f"{y(r['mujoco_load'])} | {y(r['zron_boot'])} | {y(r['setpoints_match'])} | "
                  f"{y(r['physics_finite'])} | {'PASS' if r['pass'] else 'FAIL'} |")
    md.append("")
    with open(os.path.join(out, "compat.md"), "w") as f:
        f.write("\n".join(md))

if __name__ == "__main__":
    sys.exit(main())
